# Umbriel configuration. Changes apply on save.
# See https://docs.noctalia.dev/umbriel/ for the full reference.

[include]
files = [
    "animation.toml",
    "keybinds.toml",
    "windowrules.toml",
    "outputs.toml",
    "appearance.toml",
    "layout.toml",
    "noctalia.toml"
]

[general]
autostart = [
    "noctalia",
    "equibop",
    "steam",
]
mod_key = "Super"
xwayland = true
show_cheatsheet = true
focus_on_activate = true
honor_restored_maximize = false

[workspaces]
back_and_forth = false

[overview]
zoom = 0.5

[hot_corners.top_left]
enabled = true
delay_ms = 500
action = "overview-open"

[hot_corners.top_right]
enabled = false
delay_ms = 500
action = "overview-close"

[hot_corners.bottom_left]
enabled = false
delay_ms = 500
action = "overview-toggle"

[hot_corners.bottom_right]
enabled = false
delay_ms = 500
action = "spawn:notify-send 'Bottom right'"

[input]
middle_click_paste = true

[input.keyboard]
layout = ""
variant = ""
options = ""
repeat_rate = 25
repeat_delay = 600

[input.touchpad]
tap = true

[input.mouse]
accel_profile = "flat"
sensitivity = 0.0
scroll_wheel_step = 60

[input.tablet]
enabled = true

[input.cursor]
theme = ""
size = 24
hardware_cursor = true
hide_when_typing = false
hide_timeout_ms = 0

[input.focus]
follows_mouse = false

[[layer_rule]]
match.namespace = "^noctalia-(bar-[^\"]+|notification|dock|panel|attached-panel|osd)$"
blur = true
blur_ignore_alpha = 0.5
blur_optimized = false
