[[window_rule]]
match.app_id = "^(dev.noctalia.Noctalia|xdg-desktop-portal-gtk)$"
default_floating = true
default_size = [1020, 900]

[[window_rule]]
match.app_id = "^dev.noctalia.UmbrielSharePicker$"
default_floating = true
default_size = [800, 600]

#Steam games
[[window_rule]]
match.app_id = "^steam_app.*?$"
default_floating = true
default_size = [1280, 720]
default_focused = true
default_position = { x = 0, y = 0 }
default_workspace = 3

# Steam notification toasts
[[window_rule]]
match.title = "^notificationtoasts_.+_desktop"
default_position = { x = 0, y = 0, anchor = "bottom_right" }
default_focused = false
default_pinned = true

[[window_rule]]
match.app_id = "^kitty$"
blur = true

#workspace-2 apps
[[window_rule]]
match.app_id = "^(equibop|Spotify|com.pocoguy.Muse)$"
default_workspace = 2

#workspace-3 apps
[[window_rule]]
match.app_id = "^(heroic|steam)$"
default_workspace = 3

#workspace-5 apps
[[window_rule]]
match.app_id = "^dev.zed.Zed$"
default_workspace = 5
default_floating = true

#Active/Inactive windows opacity
[[window_rule]]
match.is_focused = false
opacity = 0.95

[[window_rule]]
match.is_focused = true
opacity = 1.0
